In [54]:
import pandas as pd
import numpy as np
%config IPCompleter.greedy=True

### Requirement
We have dataset **spam.csv** which contains all email contents. This dataset is used to predict an email is ham or spam. Here is some steps need to be done
1. Read dataset and do basic analysis
2. Standardize data using CountVectorizer and TF-IDF.

In [55]:
dataset = pd.read_csv("data/spam.csv", encoding = "latin-1")
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
v1            5572 non-null object
v2            5572 non-null object
Unnamed: 2    50 non-null object
Unnamed: 3    12 non-null object
Unnamed: 4    6 non-null object
dtypes: object(5)
memory usage: 217.7+ KB

In [56]:
dataset.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [57]:
dataset = dataset.drop(["Unnamed: 2", "Unnamed: 3", "Unnamed: 4"], axis=1)

In [58]:
dataset.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [59]:
from sklearn import preprocessing
target = dataset.v1
le = preprocessing.LabelEncoder()
encode_target = pd.DataFrame(le.fit_transform(target), columns=['result'])
encode_target.head()

   result
0       0
1       0
2       1
3       0
4       0

In [60]:
le.classes_

array(['ham', 'spam'], dtype=object)

In [61]:
text = dataset[['v2']]

In [62]:
text['v2'] = text['v2'].str.lower()

/home/dat-tran/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [63]:
text['chart_cnt'] = text['v2'].str.len()
text['word_cnt'] = text['v2'].str.split().str.len()
text['avg_word_length'] = text['chart_cnt'] / text['word_cnt']

In [64]:
text.head()

,v2,chart_cnt,word_cnt,avg_word_length
0,"go until jurong point, crazy.. available only ...",111,20,5.550000
1,ok lar... joking wif u oni...,29,6,4.833333
2,free entry in 2 a wkly comp to win fa cup fina...,155,28,5.535714
3,u dun say so early hor... u c already then say...,49,11,4.454545
4,"nah i don't think he goes to usf, he lives aro...",61,13,4.692308

### We standard text data using CountVectorizer

In [65]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(stop_words='english')
cv.fit(text['v2'])

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words='english',
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [66]:
cv.get_feature_names()

['00',
 '000',
 '000pes',
 '008704050406',
 '0089',
 '0121',
 '01223585236',
 '01223585334',
 '0125698789',
 '02',
 '0207',
 '02072069400',
 '02073162414',
 '02085076972',
 '021',
 '03',
 '04',
 '0430',
 '05',
 '050703',
 '0578',
 '06',
 '07',
 '07008009200',
 '07046744435',
 '07090201529',
 '07090298926',
 '07099833605',
 '07123456789',
 '0721072',
 '07732584351',
 '07734396839',
 '07742676969',
 '07753741225',
 '0776xxxxxxx',
 '07781482378',
 '07786200117',
 '077xxx',
 '078',
 '07801543489',
 '07808',
 '07808247860',
 '07808726822',
 '07815296484',
 '07821230901',
 '078498',
 '07880867867',
 '0789xxxxxxx',
 '07946746291',
 '0796xxxxxx',
 '07973788240',
 '07xxxxxxxxx',
 '08',
 '0800',
 '08000407165',
 '08000776320',
 '08000839402',
 '08000930705',
 '08000938767',
 '08001950382',
 '08002888812',
 '08002986030',
 '08002986906',
 '08002988890',
 '08006344447',
 '0808',
 '08081263000',
 '08081560665',
 '0825',
 '083',
 '0844',
 '08448350055',
 '08448714184',
 '0845',
 '08450542832',
 '08452810071',
 '08452810073',
 '08452810075over18',
 '0870',
 '08700435505150p',
 '08700469649',
 '08700621170150p',
 '08701213186',
 '08701237397',
 '08701417012',
 '08701417012150p',
 '0870141701216',
 '087016248',
 '08701752560',
 '087018728737',
 '0870241182716',
 '08702490080',
 '08702840625',
 '08704050406',
 '08704439680',
 '08704439680ts',
 '08706091795',
 '0870737910216yrs',
 '08707500020',
 '08707509020',
 '0870753331018',
 '08707808226',
 '08708034412',
 '08708800282',
 '08709222922',
 '08709501522',
 '0871',
 '087104711148',
 '08712101358',
 '08712103738',
 '0871212025016',
 '08712300220',
 '087123002209am',
 '08712317606',
 '08712400200',
 '08712400602450p',
 '08712400603',
 '08712402050',
 '08712402578',
 '08712402779',
 '08712402902',
 '08712402972',
 '08712404000',
 '08712405020',
 '08712405022',
 '08712460324',
 '08712466669',
 '0871277810710p',
 '0871277810810',
 '0871277810910p',
 '08714342399',
 '087147123779am',
 '08714712379',
 '08714712388',
 '08714712394',
 '08714712412',
 '08714714011',
 '08715203028',
 '08715203649',
 '08715203652',
 '08715203656',
 '08715203677',
 '08715203685',
 '08715203694',
 '08715205273',
 '08715500022',
 '08715705022',
 '08717111821',
 '08717168528',
 '08717205546',
 '0871750',
 '08717507382',
 '08717509990',
 '08717890890å',
 '08717895698',
 '08717898035',
 '08718711108',
 '08718720201',
 '08718723815',
 '08718725756',
 '08718726270',
 '087187262701',
 '08718726970',
 '08718726971',
 '08718726978',
 '087187272008',
 '08718727868',
 '08718727870',
 '08718727870150ppm',
 '08718730555',
 '08718730666',
 '08718738001',
 '08718738002',
 '08718738034',
 '08719180219',
 '08719180248',
 '08719181259',
 '08719181503',
 '08719181513',
 '08719839835',
 '08719899217',
 '08719899229',
 '08719899230',
 '09',
 '09041940223',
 '09050000301',
 '09050000332',
 '09050000460',
 '09050000555',
 '09050000878',
 '09050000928',
 '09050001295',
 '09050001808',
 '09050002311',
 '09050003091',
 '09050005321',
 '09050090044',
 '09050280520',
 '09053750005',
 '09056242159',
 '09057039994',
 '09058091854',
 '09058091870',
 '09058094454',
 '09058094455',
 '09058094507',
 '09058094565',
 '09058094583',
 '09058094594',
 '09058094597',
 '09058094599',
 '09058095107',
 '09058095201',
 '09058097189',
 '09058097218',
 '09058098002',
 '09058099801',
 '09061104276',
 '09061104283',
 '09061209465',
 '09061213237',
 '09061221061',
 '09061221066',
 '09061701444',
 '09061701461',
 '09061701851',
 '09061701939',
 '09061702893',
 '09061743386',
 '09061743806',
 '09061743810',
 '09061743811',
 '09061744553',
 '09061749602',
 '09061790121',
 '09061790125',
 '09061790126',
 '09063440451',
 '09063442151',
 '09063458130',
 '0906346330',
 '09064011000',
 '09064012103',
 '09064012160',
 '09064015307',
 '09064017295',
 '09064017305',
 '09064018838',
 '09064019014',
 '09064019788',
 '09065069120',
 '09065069154',
 '09065171142',
 '09065174042',
 '09065394514',
 '09065394973',
 '09065989180',
 '09065989182',
 '09066350750',
 '09066358152',
 '09066358361',
 '09066361921',
 '09066362206',
 '09066362220',
 '09066362231',
 '09066364311',
 '09066364349',
 '09066364589',
 '09066368327',
 '09066368470',
 '09066368753',
 '09066380611',
 '09066382422',
 '09066612661',
 '09066649731from',
 '09066660100',
 '09071512432',
 '09071512433',
 '09071517866',
 '09077818151',
 '09090204448',
 '09090900040',
 '09094100151',
 '09094646631',
 '09094646899',
 '09095350301',
 '09096102316',
 '09099725823',
 '09099726395',
 '09099726429',
 '09099726481',
 '09099726553',
 '09111030116',
 '09111032124',
 '09701213186',
 '0a',
 '0quit',
 '10',
 '100',
 '1000',
 '1000call',
 '1000s',
 '100p',
 '100percent',
 '100txt',
 '1013',
 '1030',
 '10am',
 '10k',
 '10p',
 '10ppm',
 '10th',
 '11',
 '1120',
 '113',
 '1131',
 '114',
 '116',
 '1172',
 '118p',
 '11mths',
 '11pm',
 '12',
 '1205',
 '120p',
 '121',
 '1225',
 '123',
 '125',
 '1250',
 '125gift',
 '128',
 '12hours',
 '12hrs',
 '12mths',
 '13',
 '130',
 '1327',
 '139',
 '14',
 '140',
 '1405',
 '140ppm',
 '145',
 '1450',
 '146tf150p',
 '14tcr',
 '14thmarch',
 '15',
 '150',
 '1500',
 '150p',
 '150p16',
 '150pm',
 '150ppermesssubscription',
 '150ppm',
 '150ppmpobox10183bhamb64xe',
 '150ppmsg',
 '150pw',
 '151',
 '153',
 '15541',
 '15pm',
 '16',
 '165',
 '1680',
 '169',
 '177',
 '18',
 '180',
 '1843',
 '18p',
 '18yrs',
 '195',
 '1956669',
 '1apple',
 '1b6a5ecef91ff9',
 '1cup',
 '1da',
 '1er',
 '1hr',
 '1im',
 '1lemon',
 '1mega',
 '1million',
 '1pm',
 '1st',
 '1st4terms',
 '1stchoice',
 '1stone',
 '1thing',
 '1tulsi',
 '1win150ppmx3',
 '1winaweek',
 '1winawk',
 '1x150p',
 '1yf',
 '20',
 '200',
 '2000',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '200p',
 '2025050',
 '20m12aq',
 '20p',
 '21',
 '21870000',
 '21st',
 '22',
 '220',
 '220cm2',
 '2309',
 '23f',
 '23g',
 '24',
 '24hrs',
 '24m',
 '24th',
 '25',
 '250',
 '250k',
 '255',
 '25p',
 '26',
 '2667',
 '26th',
 '27',
 '28',
 '2814032',
 '28days',
 '28th',
 '28thfeb',
 '29',
 '2b',
 '2bold',
 '2c',
 '2channel',
 '2day',
 '2end',
 '2exit',
 '2ez',
 '2find',
 '2getha',
 '2geva',
 '2go',
 '2gthr',
 '2hrs',
 '2kbsubject',
 '2lands',
 '2marrow',
 '2moro',
 '2morow',
 '2morro',
 '2morrow',
 '2morrowxxxx',
 '2mro',
 '2mrw',
 '2nd',
 '2nhite',
 '2nights',
 '2nite',
 '2optout',
 '2p',
 '2price',
 '2px',
 '2rcv',
 '2stop',
 '2stoptx',
 '2stoptxt',
 '2u',
 '2u2',
 '2waxsto',
 '2wks',
 '2wt',
 '2wu',
 '2years',
 '2yr',
 '2yrs',
 '30',
 '300',
 '3000',
 '300603',
 '300603t',
 '300p',
 '3030',
 '30apr',
 '30ish',
 '30pm',
 '30pp',
 '30s',
 '30th',
 '31',
 '3100',
 '310303',
 '31p',
 '32',
 '32000',
 '3230',
 '32323',
 '326',
 '33',
 '330',
 '350',
 '3510i',
 '35p',
 '3650',
 '36504',
 '3680',
 '373',
 '3750',
 '37819',
 '38',
 '382',
 '391784',
 '3aj',
 '3d',
 '3days',
 '3g',
 '3gbp',
 '3hrs',
 '3lions',
 '3lp',
 '3miles',
 '3mins',
 '3mobile',
 '3optical',
 '3pound',
 '3qxj9',
 '3rd',
 '3ss',
 '3uz',
 '3wks',
 '3xx',
 '3xå',
 '40',
 '400',
 '400mins',
 '400thousad',
 '402',
 '4041',
 '40411',
 '40533',
 '40gb',
 '40mph',
 '41685',
 '41782',
 '420',
 '42049',
 '4217',
 '42478',
 '42810',
 '430',
 '434',
 '44',
 '440',
 '4403ldnw1a7rw18',
 '44345',
 '447797706009',
 '447801259231',
 '448712404000',
 '449050000301',
 '449071512431',
 '45',
 '450',
 '450p',
 '450pw',
 '45239',
 '45pm',
 '47',
 '4719',
 '4742',
 '47per',
 '48',
 '4882',
 '48922',
 '49',
 '49557',
 '4a',
 '4d',
 '4eva',
 '4few',
 '4fil',
 '4get',
 '4give',
 '4got',
 '4goten',
 '4info',
 '4jx',
 '4msgs',
 '4mths',
 '4qf2',
 '4t',
 '4th',
 '4the',
 '4thnov',
 '4txt',
 '4u',
 '4utxt',
 '4w',
 '4ward',
 '4wrd',
 '4xx26',
 '4years',
 '50',
 '500',
 '5000',
 '505060',
 '50award',
 '50ea',
 '50gbp',
 '50p',
 '50perweeksub',
 '50perwksub',
 '50pm',
 '50pmmorefrommobile2bremoved',
 '50ppm',
 '50rcvd',
 '50s',
 '515',
 '5226',
 '523',
 '526',
 '528',
 '530',
 '54',
 '542',
 '545',
 '5digital',
 '5free',
 '5ish',
 '5k',
 '5min',
 '5mls',
 '5p',
 '5pm',
 '5th',
 '5wb',
 '5we',
 '5wkg',
 '5wq',
 '5years',
 '60',
 '600',
 '6031',
 '6089',
 '60p',
 '61',
 '61200',
 '61610',
 '62220cncl',
 '6230',
 '62468',
 '62735',
 '630',
 '63miles',
 '645',
 '65',
 '650',
 '66',
 '6669',
 '674',
 '67441233',
 '68866',
 '69101',
 '69200',
 '69669',
 '69696',
 '69698',
 '69855',
 '69866',
 '69876',
 '69888',
 '69888nyt',
 '69911',
 '69969',
 '69988',
 '6days',
 '6hl',
 '6hrs',
 '6ish',
 '6missed',
 '6months',
 '6ph',
 '6pm',
 '6th',
 '6times',
 '6wu',
 '6zf',
 '700',
 '71',
 '7250',
 '7250i',
 '730',
 '731',
 '74355',
 '75',
 '750',
 '7548',
 '75max',
 '762',
 '7634',
 '7684',
 '77',
 '7732584351',
 '78',
 '786',
 '7876150ppm',
 '79',
 '7am',
 '7cfca1a',
 '7ish',
 '7mp',
 '7oz',
 '7pm',
 '7th',
 '7ws',
 '7zs',
 '80',
 '800',
 '8000930705',
 '80062',
 '8007',
 '80082',
 '80086',
 '80122300p',
 '80155',
 '80160',
 '80182',
 '8027',
 '80488',
 '80608',
 '8077',
 '80878',
 '81010',
 '81151',
 '81303',
 '81618',
 '82050',
 '820554ad0a1705572711',
 '82242',
 '82277',
 '82324',
 '82468',
 '83021',
 '83039',
 '83049',
 '83110',
 '83118',
 '83222',
 '83332',
 '83338',
 '83355',
 '83370',
 '83383',
 '83435',
 '83600',
 '83738',
 '84',
 '84025',
 '84122',
 '84128',
 '84199',
 '84484',
 '85',
 '850',
 '85023',
 '85069',
 '85222',
 '85233',
 '8552',
 '85555',
 '86021',
 '861',
 '864233',
 '86688',
 '86888',
 '87021',
 '87066',
 '87070',
 '87077',
 '87121',
 '87131',
 '8714714',
 '872',
 '87239',
 '87575',
 '8800',
 '88039',
 '88066',
 '88088',
 '88222',
 '88600',
 '88800',
 '8883',
 '88877',
 '88888',
 '89034',
 '89070',
 '89080',
 '89105',
 '89123',
 '89545',
 '89555',
 '89693',
 '89938',
 '8am',
 '8ball',
 '8lb',
 '8p',
 '8pm',
 '8th',
 '8wp',
 '900',
 '9061100010',
 '910',
 '9153',
 '9280114',
 '930',
 '9307622',
 '945',
 '946',
 '95',
 '9755',
 '9758',
 '97n7qp',
 '98321561',
 '99',
 '9996',
 '9ae',
 '9am',
 '9ja',
 '9pm',
 '9t',
 '9th',
 '9yt',
 '____',
 'a21',
 'a30',
 'aa',
 'aah',
 'aaniye',
 'aaooooright',
 'aathi',
 'ab',
 'abbey',
 'abdomen',
 'abeg',
 'abel',
 'aberdeen',
 'abi',
 'ability',
 'abiola',
 'abj',
 'able',
 'abnormally',
 'aboutas',
 'abroad',
 'absence',
 'absolutely',
 'absolutly',
 'abstract',
 'abt',
 'abta',
 'aburo',
 'abuse',
 'abusers',
 'ac',
 'academic',
 'acc',
 'accent',
 'accenture',
 'accept',
 'access',
 'accessible',
 'accidant',
 'accident',
 'accidentally',
 'accommodation',
 'accommodationvouchers',
 'accomodate',
 'accomodations',
 'accordin',
 'accordingly',
 'account',
 'accounting',
 'accounts',
 'accumulation',
 'achan',
 'ache',
 'achieve',
 'acid',
 'acknowledgement',
 'acl03530150pm',
 'acnt',
 'aco',
 'act',
 'acted',
 'actin',
 'acting',
 'action',
 'activ8',
 'activate',
 'active',
 'activities',
 'actor',
 'actual',
 'actually',
 'ad',
 'adam',
 'add',
 'addamsfa',
 'added',
 'addicted',
 'addie',
 'adding',
 'address',
 'adds',
 'adewale',
 'adi',
 'adjustable',
 'admin',
 'administrator',
 'admirer',
 'admission',
 'admit',
 'adore',
 'adoring',
 'adp',
 'adress',
 'adrian',
 'ads',
 'adsense',
 'adult',
 'adults',
 'advance',
 'adventure',
 'adventuring',
 'advice',
 'advise',
 'advising',
 'advisors',
 'aeronautics',
 'aeroplane',
 'afew',
 'affair',
 'affairs',
 'affection',
 'affectionate',
 'affections',
 'affidavit',
 'afford',
 'afghanistan',
 'afraid',
 'africa',
 'african',
 'aft',
 'afternon',
 'afternoon',
 'afternoons',
 'aftr',
 'ag',
 'agalla',
 'age',
 'age16',
 'age23',
 'agency',
 'agent',
 'agents',
 'ages',
 'agidhane',
 'aging',
 'ago',
 'agree',
 'ah',
 'aha',
 'ahead',
 'ahhh',
 'ahhhh',
 'ahmad',
 'ahold',
 'aid',
 'aids',
 'aig',
 'aight',
 'ain',
 'aint',
 'air',
 'air1',
 'airport',
 'airtel',
 'aiya',
 'aiyah',
 'aiyar',
 'aiyo',
 'ajith',
 'ak',
 ...]

In [67]:
text_transfom = cv.transform(text['v2'])

In [68]:
text_transfom.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [69]:
df_text = pd.DataFrame(text_transfom.toarray(), columns=cv.get_feature_names())

In [70]:
df_text.head()

,00,000,000pes,008704050406,0089,0121,01223585236,01223585334,0125698789,02,...,ó_,û_,û_thanks,ûªm,ûªt,ûªve,ûï,ûïharry,ûò,ûówell
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [71]:
df_text.shape

(5572, 8404)

In [72]:
new_dataset = pd.concat([df_text, pd.DataFrame(encode_target)], axis= 1)

In [73]:
new_dataset.head()

,00,000,000pes,008704050406,0089,0121,01223585236,01223585334,0125698789,02,...,û_,û_thanks,ûªm,ûªt,ûªve,ûï,ûïharry,ûò,ûówell,result
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### We standardize using TF-IDF method

In [74]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv = TfidfVectorizer(max_features = 1000, stop_words='english')
tv.fit(text['v2'])
tv_transform = tv.transform(text['v2'])

In [75]:
tv_transform.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [76]:
df_text = pd.DataFrame(tv_transform.toarray(), columns=tv.get_feature_names())

In [77]:
new_dataset = pd.concat([df_text, pd.DataFrame(encode_target)], axis= 1)

In [78]:
new_dataset.head()

,00,000,02,03,04,06,0800,08000839402,08000930705,0870,...,yes,yesterday,yo,yr,yup,ì_,ìï,û_,ûò,result
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

### TF-IDF với N-grams

In [79]:
tv_ngram = TfidfVectorizer(max_features = 1000, stop_words='english', ngram_range=(1,2))
tv_ngram.fit(text['v2'])
tv_ngram_tranform = tv_ngram.transform(text['v2'])

In [80]:
tv_ngram.get_feature_names()

['00',
 '000',
 '03',
 '04',
 '0800',
 '08000839402',
 '08000930705',
 '10',
 '100',
 '1000',
 '1000 cash',
 '10p',
 '10p min',
 '11',
 '12',
 '12hrs',
 '150',
 '150p',
 '150p msg',
 '150ppm',
 '16',
 '18',
 '1st',
 '1st week',
 '20',
 '200',
 '2000',
 '2000 prize',
 '2003',
 '2003 account',
 '250',
 '2lands',
 '2lands row',
 '2nd',
 '2nd attempt',
 '2nite',
 '30',
 '350',
 '350 award',
 '50',
 '500',
 '5000',
 '750',
 '800',
 '800 redeemed',
 '8007',
 '86688',
 '86688 150p',
 '87066',
 '900',
 'abiola',
 'able',
 'abt',
 'ac',
 'account',
 'account statement',
 'actually',
 'address',
 'admirer',
 'aft',
 'afternoon',
 'age',
 'ago',
 'ah',
 'aight',
 'alright',
 'amp',
 'angry',
 'ans',
 'answer',
 'anytime',
 'apply',
 'ard',
 'area',
 'asap',
 'ask',
 'askd',
 'asked',
 'asking',
 'ass',
 'attempt',
 'attempt contact',
 'auction',
 'available',
 'await',
 'await collection',
 'award',
 'awarded',
 'away',
 'awesome',
 'b4',
 'babe',
 'baby',
 'bad',
 'balance',
 'bank',
 'bath',
 'bathe',
 'bcoz',
 'beautiful',
 'bed',
 'believe',
 'best',
 'better',
 'big',
 'birthday',
 'bit',
 'blood',
 'blue',
 'bonus',
 'bonus caller',
 'book',
 'booked',
 'bored',
 'bout',
 'box',
 'boy',
 'boytoy',
 'break',
 'bring',
 'brother',
 'bslvyl',
 'bt',
 'bt national',
 'bus',
 'busy',
 'buy',
 'call2optout',
 'called',
 'caller',
 'caller prize',
 'callertune',
 'calling',
 'calls',
 'camcorder',
 'camcorder reply',
 'came',
 'camera',
 'car',
 'card',
 'care',
 'carlos',
 'case',
 'cash',
 'cash await',
 'cause',
 'chance',
 'chance win',
 'change',
 'charge',
 'charged',
 'chat',
 'chat 86688',
 'cheap',
 'check',
 'checking',
 'chennai',
 'chikku',
 'choose',
 'christmas',
 'claim',
 'claim code',
 'claim ur',
 'class',
 'clean',
 'close',
 'club',
 'code',
 'collect',
 'collection',
 'college',
 'colour',
 'com',
 'come',
 'come home',
 'come tomorrow',
 'comes',
 'comin',
 'coming',
 'comp',
 'company',
 'complimentary',
 'computer',
 'confirm',
 'congrats',
 'congratulations',
 'contact',
 'content',
 'convey',
 'cool',
 'correct',
 'cos',
 'cost',
 'couple',
 'course',
 'coz',
 'crave',
 'crazy',
 'credit',
 'cs',
 'cum',
 'currently',
 'custcare',
 'customer',
 'customer service',
 'customer services',
 'cut',
 'da',
 'dad',
 'darlin',
 'darren',
 'dat',
 'date',
 'dating',
 'dating service',
 'day',
 'days',
 'dear',
 'decided',
 'decimal',
 'decimal gt',
 'deep',
 'del',
 'delivery',
 'den',
 'details',
 'did',
 'didn',
 'didnt',
 'die',
 'different',
 'difficult',
 'dinner',
 'direct',
 'dis',
 'discount',
 'dnt',
 'does',
 'doesn',
 'dogging',
 'doin',
 'doing',
 'don',
 'don know',
 'don think',
 'dont',
 'dont know',
 'double',
 'double mins',
 'download',
 'draw',
 'draw shows',
 'dream',
 'dreams',
 'drink',
 'drive',
 'driving',
 'drop',
 'drugs',
 'dude',
 'dun',
 'dun wan',
 'dunno',
 'earlier',
 'early',
 'easy',
 'eat',
 'eh',
 'em',
 'email',
 'end',
 'ends',
 'energy',
 'england',
 'enjoy',
 'enter',
 'entered',
 'entry',
 'eve',
 'evening',
 'ex',
 'exam',
 'expires',
 'extra',
 'face',
 'fact',
 'family',
 'fancy',
 'fantastic',
 'far',
 'fast',
 'father',
 'feel',
 'feel like',
 'feeling',
 'feels',
 'felt',
 'figure',
 'film',
 'final',
 'finally',
 'fine',
 'finish',
 'finished',
 'fone',
 'food',
 'forget',
 'forgot',
 'fr',
 'free',
 'free entry',
 'free text',
 'freemsg',
 'fri',
 'friday',
 'friend',
 'friends',
 'friendship',
 'frm',
 'frnd',
 'frnds',
 'fuck',
 'fucking',
 'fun',
 'gal',
 'game',
 'games',
 'gas',
 'gave',
 'gd',
 'ge',
 'gets',
 'gettin',
 'getting',
 'getzed',
 'getzed uk',
 'gift',
 'girl',
 'girls',
 'glad',
 'gn',
 'god',
 'goes',
 'goes day',
 'goin',
 'going',
 'gone',
 'gonna',
 'good',
 'good afternoon',
 'good day',
 'good morning',
 'good night',
 'goodmorning',
 'got',
 'gotta',
 'gr8',
 'great',
 'great day',
 'grins',
 'gt',
 'gt lt',
 'gt min',
 'guaranteed',
 'guaranteed 1000',
 'gud',
 'gud mrng',
 'gud ni8',
 'guess',
 'guy',
 'guys',
 'gym',
 'ha',
 'haf',
 'haha',
 'hair',
 'half',
 'half price',
 'hand',
 'happen',
 'happened',
 'happiness',
 'happy',
 'happy birthday',
 'happy new',
 'hard',
 'hav',
 'haven',
 'havent',
 'having',
 'head',
 'hear',
 'heard',
 'heart',
 'hee',
 'hello',
 'help',
 'hey',
 'hg',
 'hg suite342',
 'hi',
 'hi darlin',
 'hi hi',
 'hit',
 'hmm',
 'hmmm',
 'hmv',
 'ho',
 'hold',
 'holiday',
 'holiday 5000',
 'home',
 'hope',
 'hope good',
 'hope having',
 'hoping',
 'hospital',
 'hot',
 'hour',
 'hours',
 'house',
 'hows',
 'http',
 'http www',
 'huh',
 'hungry',
 'hurt',
 'hw',
 'id',
 'identifier',
 'identifier code',
 'il',
 'ill',
 'im',
 'immediately',
 'important',
 'india',
 'info',
 'information',
 'invited',
 'ipod',
 'isn',
 'jay',
 'job',
 'john',
 'join',
 'joy',
 'jus',
 'just',
 'just got',
 'just text',
 'just txt',
 'juz',
 'kate',
 'kids',
 'kind',
 'kiss',
 'knew',
 'know',
 'knows',
 'knw',
 'land',
 'land line',
 'landline',
 'laptop',
 'lar',
 'late',
 'later',
 'latest',
 'laugh',
 'ldn',
 'leave',
 'leaves',
 'leaving',
 'left',
 'leh',
 'lei',
 'lesson',
 'let',
 'let know',
 'lets',
 'liao',
 'life',
 'light',
 'like',
 'like lt',
 'line',
 'line claim',
 'line rental',
 'link',
 'listen',
 'little',
 'live',
 'live operator',
 'll',
 'll later',
 'll text',
 'loads',
 'log',
 'lol',
 'long',
 'look',
 'looking',
 'lor',
 'lose',
 'lost',
 'lot',
 'lots',
 'lovable',
 'love',
 'loved',
 'lovely',
 'loving',
 'lt',
 'lt decimal',
 'lt gt',
 'luck',
 'lucky',
 'lunch',
 'luv',
 'mah',
 'mail',
 'make',
 'makes',
 'making',
 'man',
 'march',
 'match',
 'mate',
 'mates',
 'mayb',
 'maybe',
 'mean',
 'means',
 'meant',
 'meet',
 'meeting',
 'merry',
 'message',
 'messages',
 'met',
 'min',
 'mind',
 'mins',
 'minute',
 'minutes',
 'miss',
 'missed',
 'missing',
 'mm',
 'mob',
 'mobile',
 'mobile number',
 'mobiles',
 'mobileupd8',
 'mom',
 'moment',
 'monday',
 'money',
 'month',
 'months',
 'morning',
 'motorola',
 'movie',
 'mr',
 'mrng',
 'msg',
 'msgs',
 'mu',
 'mum',
 'music',
 'music 87066',
 'muz',
 'na',
 'nah',
 'national',
 'national rate',
 'need',
 'needs',
 'net',
 'network',
 'network mins',
 'neva',
 'new',
 'new video',
 'new year',
 'news',
 'ni8',
 'nice',
 'nice day',
 'night',
 'nite',
 'noe',
 'nokia',
 'nope',
 'normal',
 'nt',
 'ntt',
 'ntt po',
 'number',
 'numbers',
 'nyt',
 'offer',
 'offers',
 'office',
 'oh',
 'ok',
 'ok lor',
 'okay',
 'okie',
 'old',
 'online',
 'oops',
 'open',
 'operator',
 'opt',
 'orange',
 'orchard',
 'order',
 'oredi',
 'oso',
 'outside',
 'pa',
 'pain',
 'paper',
 'parents',
 'park',
 'party',
 'pass',
 'pay',
 'people',
 'person',
 'pete',
 'phone',
 'phone right',
 'phones',
 'pic',
 'pick',
 'pick phone',
 'picking',
 'pics',
 'place',
 'plan',
 'plans',
 'play',
 'player',
 'pls',
 'pls send',
 'plus',
 'plz',
 'pm',
 'po',
 'po box',
 'pobox',
 'point',
 'points',
 'police',
 'poly',
 'poor',
 'post',
 'pounds',
 'pray',
 'press',
 'pretty',
 'price',
 'princess',
 'private',
 'private 2003',
 'prize',
 'prize claim',
 'prize guaranteed',
 'prob',
 'probably',
 'problem',
 'project',
 'pub',
 'question',
 'questions',
 'quite',
 'quiz',
 'rakhesh',
 'rate',
 'rates',
 'reach',
 'reached',
 'read',
 'reading',
 'ready',
 'real',
 'really',
 'reason',
 'receive',
 'receive 350',
 'red',
 'redeemed',
 'redeemed points',
 'remember',
 'remove',
 'rental',
 'reply',
 'reply 08000930705',
 'reply stop',
 'representative',
 'rest',
 'reveal',
 'reveal thinks',
 'reward',
 'right',
 'right pls',
 'ring',
 'ringtone',
 'ringtones',
 'rite',
 'rock',
 'room',
 'row',
 'row w1j6hl',
 'rply',
 'rs',
 'run',
 'sad',
 'sae',
 'sae cs',
 'safe',
 'said',
 'sat',
 'saturday',
 'savamob',
 'save',
 'saw',
 'say',
 'saying',
 'says',
 'sch',
 'school',
 'sea',
 'search',
 'second',
 'secret',
 'secret admirer',
 'seeing',
 'seen',
 'selected',
 'selected receive',
 'sell',
 'semester',
 'send',
 'send message',
 'send stop',
 'sending',
 'sent',
 'service',
 'service representative',
 'services',
 'set',
 'sex',
 'sexy',
 'shall',
 'shit',
 'shop',
 'shopping',
 'shower',
 'shows',
 'shows 800',
 'shows won',
 'simple',
 'sir',
 'sis',
 'sister',
 'sleep',
 'sleeping',
 'slow',
 'slowly',
 'small',
 'smile',
 'smiling',
 'smoke',
 'sms',
 'sms ac',
 'smth',
 'snow',
 'somebody',
 'song',
 'sony',
 'soon',
 'sorry',
 'sorry ll',
 'sort',
 'sound',
 'sounds',
 'speak',
 'speak live',
 'special',
 'spend',
 'st',
 'start',
 'started',
 'statement',
 'stay',
 'staying',
 'std',
 'stop',
 'stop texts',
 'store',
 'story',
 'study',
 'stuff',
 'stupid',
 'sub',
 'suite342',
 'suite342 2lands',
 'sun',
 'sunday',
 'support',
 'supposed',
 'sure',
 'surprise',
 'sweet',
 'swing',
 'takes',
 'taking',
 'talk',
 'talking',
 'tc',
 'tel',
 'tell',
 'tell ur',
 'telling',
 'terms',
 'test',
 'text',
 'texts',
 'th',
 'thank',
 'thanks',
 'thanx',
 'thats',
 'thing',
 'things',
 'think',
 'thinking',
 'thinks',
 'thk',
 'tho',
 'thought',
 'tickets',
 'til',
 'till',
 'time',
 'times',
 'tired',
 'tmr',
 'today',
 'todays',
 'told',
 'tomo',
 'tomorrow',
 'tone',
 'tone ur',
 'tones',
 'tonight',
 'tonite',
 'took',
 'tot',
 'touch',
 'town',
 'train',
 'treat',
 'tried',
 'tried contact',
 'trip',
 'true',
 'truth',
 'try',
 'trying',
 'trying contact',
 'ts',
 'ts cs',
 'tv',
 'txt',
 'txt nokia',
 'txt stop',
 'txt word',
 'txting',
 'txts',
 'type',
 'ugh',
 'uk',
 'uncle',
 'understand',
 'unlimited',
 'unsubscribe',
 'update',
 'ur',
 'ur awarded',
 'ur cash',
 'ur friends',
 'ur mates',
 'ur mob',
 'ur mobile',
 'urgent',
 'urgent mobile',
 'urgent trying',
 'use',
 'used',
 'usf',
 'usual',
 'valid',
 'valid 12hrs',
 'valued',
 've',
 've got',
 'video',
 'visit',
 'voice',
 'voucher',
 'vouchers',
 'w1j6hl',
 'wait',
 'waiting',
 'wake',
 'walk',
 'wan',
 'wana',
 'wanna',
 'want',
 'want come',
 'want new',
 'wanted',
 'wants',
 'wap',
 'warm',
 'wasn',
 'wat',
 'wat doing',
 'wat time',
 'watch',
 'watching',
 'watching tv',
 'water',
 'way',
 'week',
 'week just',
 'weekend',
 'weekly',
 'weeks',
 'welcome',
 'wen',
 'went',
 'whats',
 'wid',
 'wif',
 'wife',
 'wil',
 'win',
 'wine',
 'winner',
 'wish',
 'wishing',
 'wit',
 'wk',
 'wk txt',
 'wkly',
 'woke',
 'won',
 'won 000',
 'won guaranteed',
 'wonder',
 'wonderful',
 'wont',
 'word',
 'words',
 'work',
 'working',
 'world',
 'worried',
 'worry',
 'worth',
 'wot',
 'wow',
 'write',
 'wrong',
 'www',
 'xmas',
 'xx',
 'xxx',
 'ya',
 'yar',
 'yeah',
 'year',
 'years',
 'yep',
 'yes',
 'yesterday',
 'yo',
 'yr',
 'yup',
 'ì_',
 'ìï',
 'û_']

In [81]:
tv_ngram_tranform.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [82]:
df_text = pd.DataFrame(tv_ngram_tranform.toarray(), columns=tv_ngram.get_feature_names())

In [83]:
df_text.head()

,00,000,03,04,0800,08000839402,08000930705,10,100,1000,...,years,yep,yes,yesterday,yo,yr,yup,ì_,ìï,û_
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0